"""Added MaterialsRecycled model

Revision ID: 864a3ae9ac30
Revises: bd306736a6da
Create Date: 2024-06-20 10:13:14.475729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '864a3ae9ac30'
down_revision = 'bd306736a6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recycling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material', sa.String(length=120), nullable=False))
        batch_op.drop_column('materials')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recycling', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('material')

    # ### end Alembic commands ###
